#!/bin/bash -e

if [ "${BASH_SOURCE[0]}" == "${0}" ];
then
    echo ""
    echo "This script is not being sourced"
    echo ""
    exit 1
fi


if [[ $HOSTNAME != chinook* ]];
then
    echo ""
    echo "This script works only on chinook*.alaska.edu"
    echo ""
    return 1
fi


# load gfortran/openmpi/CUDA
module load mpi/OpenMPI/1.10.3-GCC-5.4.0-2.26
module load CUDA/9.2.148_396.37
export CUDA_LIB="/opt/nvidia/cuda-9.2.148_396.37/lib64"

# load python
module load lang/Python/2.7.12-pic-intel-2016b

# activate virutal environment
source $HOME/virtual/activate-obspy2


