#!/bin/bash -e

# INSTALLS INSTASEIS ON CHINOOK


VENV="$HOME/virtual/instaseis3"
if [ -e $VENV ]; then
    echo
    echo "Directory exists: $VENV"
    echo
    exit 1
fi

# create and activate virtual environment
module load lang/Python/3.5.2-pic-intel-2016b
virtualenv $VENV
source "$VENV/bin/activate"


pip install numpy 
pip install instaseis

