#!/bin/bash -e

# INSTALLS OBSPY ON CHINOOK


VENV="$HOME/virtual/axisem"
if [ -e $VENV ]; then
    echo
    echo "Directory exists: $VENV"
    echo
    exit 1
fi

# create and activate virtual environment
module load lang/Python/3.5.2-foss-2016b
virtualenv $VENV
source "$VENV/bin/activate"

pip install numpy
pip install obspy
pip install netcdf4

